services:
  klipper:
    image: klipper:latest
    build:
      context: docker/klipper
      target: run
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32f103xe_37FFD7054246383412640557-if00:/dev/serial/by-id/usb-Klipper_stm32f103xe_37FFD7054246383412640557-if00

  moonraker:
    image: moonraker:latest
    build:
      context: docker/moonraker
      target: run

  tools:
    image: klipper:latest-tools
    build:
      context: docker/klipper
      target: tools
